stages:
  - test
  - release

pytest:
  stage: test
  tags:
    - fastapi
  script: "cargo test"

cargo_build:
  stage: release
  tags:
    - fastapi
  script: "cargo build --release && scp target/release/hyperapi gitlab-runner@10.0.49.83:/home/gitlab-runner/tianju/releases/hyperapi-0.1-x86_64-linux"
