stages:
  - build
  - test
  - release

prepare:
  stage: build
  tags:
    - fastapi
  script: "pyenv activate py38 && pip install -r requirements.txt"

gateway_test:
  stage: test
  tags:
    - fastapi
  script: "cargo build && cargo test && cd tests/ && pyenv activate py38 && python gateway_test.py"

cargo_build:
  stage: release
  tags:
    - fastapi
  script: "cargo build --release && scp target/release/hyperapi gitlab-runner@10.0.49.83:/home/gitlab-runner/tianju/releases/hyperapi-0.1-x86_64-linux"
  only:
    - master