[package]
name = "hyperapi"
version = "0.1.0"
authors = ["Leric Zhang <leric.zhang@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
log = "0.4"
tokio = { version = "0.2", features = ["full"] }
clap = "2.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
tower = "0.3"
tower-balance = "0.3"
tower-load = "0.3"
tower-discover = "0.3"
pin-project = "0.4"
futures = "0.3"
futures-util = "0.3"
anyhow = "1.0"
rand = "0.7"
tracing = "0.1"
r2d2 = "0.8"
hyper-rustls = "0.21"
rustls = "0.18"
tokio-rustls = "0.14"
base64 = "0.13"
jsonwebtoken = "7"
regex = "1.4"
env_logger = "0.8"

