apihub:
  env: office
  listen: 0.0.0.0:8888
  ssl_certificate: ""
  ssl_certificate_key: ""

  filters_setting:
    cache:
      backend: redis://localhost:6379/1
    rate_limit:
      backend: redis://localhost:6379/2

  config_provider: "https://apihub.leric.net/gw/438952832y8f78w7a8378hf43"
  reload_trigger: "poll"

  apps:
    - app_id: platform.crm
      app_key: 1345432321
      app_secret: 4535324321
      ip_whitelist: ["192.168.0.0/16"]
      services:
        account_service:
          - type: RateLimit
            methods: "GET,POST"
            path_pattern: ".*"
            limits:
              - {duration: 1, limit: 10, burst: 100}
              - {duration: 3600, limit: 10000, burst: 10000}

  services:
    - service_id: account_service 
      endpoint: account         # api url first segment
      api: juhe_account
      api_type: rest
      auth:
        type: AppKey
      timeout: 3000
      log_detail: false
      upstreams:
        - { target: "http://127.0.0.1:8000/" }
      filters:
        - type: Header
          methods: "GET,POST"
          path_pattern: ".*"
          request_inject:
            X-Authentication: "source-authenticate-token"
          request_remove:
            - "Authentication"
          response_inject:
            X-Powered-By: "juhe_api_gateway"
          response_remove:
            - "etag"
            - "cache_control"
        - type: RateLimit
          methods: "GET,POST"
          path_pattern: ".*"
          limits:
            - {duration: 1, limit: 100, burst: 500}

