services:
  - service_id: leric/account_service
    path: account     # api url first segment
    protocol: http
    auth:
      type: AppKey
    timeout: 10
    load_balance: "hash"
    upstreams:
      - { id: 12, timeout: 10, target: "http://127.0.0.1:8000/" }
    filters:
      - type: Header
        setting:
          operate_on: "request"
          injection:
            - ['X-Authentication', "source-authenticate-token"]
          removal:
            - "Authentication"
      - type: ACL
        setting:
          access_control: "allow"
          paths:
            - methods: "GET,POST,DELETE,PUT,OPTIONS,PATCH"
              path_regex: "/user/.*"

    sla:
      - name: Default
        filters:
          - type: RateLimit
            setting:
              interval: 60
              limit: 100
              burst: 100
          - type: RateLimit
            setting:
              interval: 1
              limit: 100
              burst: 200

clients:
  - client_id: account/crm
    app_key: 1345432321
    ip_whitelist: []
    services:
      leric/account_service: Default

