name: Rust

on:
  push:
    branches: [ master, devleop ]
  pull_request:
    branches: [ master, devleop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test --verbose
        cd tests && python gateway_test.py

